import type { DiagnosticCategory, DiagnosticDetectorType, DiagnosticRuleConfig, DiagnosticSeverity } from "@/domain/types";

export const DIAGNOSTIC_SCHEMA_VERSION = 2;
export const DEFAULT_RULES_VERSION = 2;

interface RuleInput {
  id: string;
  name: string;
  category: DiagnosticCategory;
  severity: DiagnosticSeverity;
  wotOnly?: boolean;
  detector?: DiagnosticDetectorType;
  conditions?: DiagnosticRuleConfig["conditions"];
  parameters?: Record<string, number>;
  durationMs?: number;
  cooldownMs?: number;
  recommendedChannels: string[];
  message: string;
  possibleCauses?: string[];
  detectorOptions?: DiagnosticRuleConfig["detectorOptions"];
  criticalCondition?: DiagnosticRuleConfig["criticalCondition"];
}

function rule(input: RuleInput): DiagnosticRuleConfig {
  return {
    id: input.id, name: input.name, category: input.category, enabled: true, wotOnly: input.wotOnly ?? (input.detector !== "pull"), severity: input.severity,
    origin: "default", modified: false, detector: input.detector ?? "temporal", conditions: input.conditions ?? [], parameters: input.parameters ?? {},
    durationMs: input.durationMs ?? 100, cooldownMs: input.cooldownMs ?? 500, correlationWindowMs: 500,
    recommendedChannels: input.recommendedChannels, message: input.message, possibleCauses: input.possibleCauses ?? [], detectorOptions: input.detectorOptions ?? {}, criticalCondition: input.criticalCondition,
  };
}

const loadConditions = [
  { left: "[throttle.actual]", operator: ">" as const, right: "MIN_THROTTLE" },
  { left: "[engine.rpm]", operator: ">" as const, right: "MIN_RPM" },
];

export function createDefaultDiagnosticRules(): DiagnosticRuleConfig[] {
  return [
    rule({ id: "boost-under-target", name: "Boost Under Target", category: "Boost", severity: "warning", conditions: [{ left: "[boost.actual]", operator: "<", right: "[boost.target] - BOOST_ERROR_WARNING" }, ...loadConditions], parameters: { BOOST_ERROR_WARNING: 0.3, BOOST_ERROR_CRITICAL: 0.55, MIN_THROTTLE: 80, MIN_RPM: 2500 }, durationMs: 250, recommendedChannels: ["engine.rpm", "throttle.actual", "boost.target", "boost.actual"], message: "Boost remained below requested target under load.", possibleCauses: ["Boost control limitation", "Charge-air leak", "Wastegate control issue"], criticalCondition: { left: "[boost.actual]", operator: "<", right: "[boost.target] - BOOST_ERROR_CRITICAL" } }),
    rule({ id: "boost-over-target", name: "Boost Over Target", category: "Boost", severity: "warning", conditions: [{ left: "[boost.actual]", operator: ">", right: "[boost.target] + BOOST_ERROR_WARNING" }, ...loadConditions], parameters: { BOOST_ERROR_WARNING: 0.25, BOOST_ERROR_CRITICAL: 0.5, MIN_THROTTLE: 80, MIN_RPM: 2500 }, durationMs: 120, recommendedChannels: ["engine.rpm", "throttle.actual", "boost.target", "boost.actual"], message: "Boost exceeded requested target.", possibleCauses: ["Boost control overshoot", "Wastegate response delay"], criticalCondition: { left: "[boost.actual]", operator: ">", right: "[boost.target] + BOOST_ERROR_CRITICAL" } }),
    rule({ id: "unexpected-boost-drop", name: "Unexpected Boost Drop", category: "Boost", severity: "warning", detector: "sudden-drop", conditions: loadConditions, parameters: { BOOST_DROP: 0.45, LOOKBACK_MS: 250, MIN_THROTTLE: 85, MIN_RPM: 2500 }, durationMs: 40, recommendedChannels: ["engine.rpm", "driver.pedal", "throttle.actual", "boost.actual", "torque.state", "transmission.gear"], message: "Boost dropped rapidly while driver demand remained high.", possibleCauses: ["Throttle or torque intervention", "Boost control interruption", "Gear shift correlation"], detectorOptions: { channel: "boost.actual", deltaParameter: "BOOST_DROP", lookbackParameter: "LOOKBACK_MS" } }),
    rule({ id: "throttle-closure", name: "Unexpected Throttle Closure", category: "Torque", severity: "warning", conditions: [{ left: "[driver.pedal]", operator: ">", right: "MIN_PEDAL" }, { left: "[throttle.actual]", operator: "<", right: "MAX_THROTTLE" }], parameters: { MIN_PEDAL: 90, MAX_THROTTLE: 70, CRITICAL_THROTTLE: 40 }, durationMs: 50, recommendedChannels: ["driver.pedal", "throttle.actual", "engine.rpm", "torque.request", "torque.actual", "torque.state", "boost.actual"], message: "Throttle closed despite high driver demand.", possibleCauses: ["Torque intervention", "Traction control", "Protection strategy"], criticalCondition: { left: "[throttle.actual]", operator: "<", right: "CRITICAL_THROTTLE" } }),
    rule({ id: "torque-intervention", name: "Torque Intervention", category: "Torque", severity: "warning", conditions: [{ left: "[torque.actual]", operator: "<", right: "[torque.request] - TORQUE_ERROR" }, { left: "[throttle.actual]", operator: ">", right: "MIN_THROTTLE" }], parameters: { TORQUE_ERROR: 120, MIN_THROTTLE: 70 }, durationMs: 100, recommendedChannels: ["engine.rpm", "throttle.actual", "torque.request", "torque.actual", "torque.limit", "torque.state"], message: "Actual torque remained substantially below requested torque.", possibleCauses: ["ECU torque limitation", "Traction or gearbox intervention"] }),
    rule({ id: "ignition-retard", name: "Ignition Retard", category: "Ignition", severity: "warning", detector: "group-temporal", conditions: [{ left: "[SIGNAL]", operator: "<", right: "WARNING_RETARD" }], parameters: { WARNING_RETARD: -3, CRITICAL_RETARD: -6 }, durationMs: 50, recommendedChannels: ["engine.rpm", "boost.actual", "throttle.actual", "ignition.cylinder.*", "ignition.total"], message: "Strong ignition retard was detected.", possibleCauses: ["Combustion correction", "Protection intervention"], detectorOptions: { group: "ignition.cylinder", fallback: "ignition.total", signalToken: "SIGNAL", peakDirection: "min" }, criticalCondition: { left: "[SIGNAL]", operator: "<", right: "CRITICAL_RETARD" } }),
    rule({ id: "cylinder-ignition-deviation", name: "Cylinder Ignition Deviation", category: "Ignition", severity: "warning", detector: "cylinder-deviation", parameters: { MAX_DEVIATION: 5, CRITICAL_DEVIATION: 8 }, durationMs: 50, recommendedChannels: ["engine.rpm", "boost.actual", "ignition.cylinder.*"], message: "One cylinder deviated from the median ignition timing.", possibleCauses: ["Cylinder-specific combustion correction", "Signal inconsistency"], detectorOptions: { group: "ignition.cylinder", thresholdParameter: "MAX_DEVIATION", criticalParameter: "CRITICAL_DEVIATION" } }),
    rule({ id: "knock-retard", name: "Knock Retard", category: "Knock", severity: "warning", detector: "group-temporal", conditions: [{ left: "[SIGNAL]", operator: "<", right: "WARNING_RETARD" }], parameters: { WARNING_RETARD: -3, CRITICAL_RETARD: -6 }, durationMs: 40, recommendedChannels: ["engine.rpm", "boost.actual", "throttle.actual", "knock.cylinder.*"], message: "Knock retard crossed the configured threshold.", possibleCauses: ["Detected combustion knock pattern", "Transient correction or noisy signal"], detectorOptions: { group: "knock.cylinder", signalToken: "SIGNAL", peakDirection: "min" }, criticalCondition: { left: "[SIGNAL]", operator: "<", right: "CRITICAL_RETARD" } }),
    rule({ id: "repeated-cylinder-knock", name: "Repeated Cylinder Knock", category: "Knock", severity: "warning", detector: "repeated-group", parameters: { WARNING_RETARD: -2.5, CRITICAL_RETARD: -6, MIN_EVENTS: 3, WINDOW_MS: 5000 }, recommendedChannels: ["engine.rpm", "boost.actual", "throttle.actual", "knock.cylinder.*"], message: "Repeated knock-retard events occurred on the same cylinder.", possibleCauses: ["Persistent cylinder-specific combustion correction"], detectorOptions: { group: "knock.cylinder", thresholdParameter: "WARNING_RETARD", countParameter: "MIN_EVENTS", windowParameter: "WINDOW_MS" } }),
    rule({ id: "fuel-pressure-below-target", name: "Fuel Pressure Below Target", category: "Fuel", severity: "critical", conditions: [{ left: "[fuel.high.actual]", operator: "<", right: "[fuel.high.target] * WARNING_RATIO" }, ...loadConditions], parameters: { WARNING_RATIO: 0.9, CRITICAL_RATIO: 0.8, MIN_THROTTLE: 80, MIN_RPM: 3000 }, durationMs: 200, cooldownMs: 1000, recommendedChannels: ["fuel.high.actual", "fuel.high.target", "fuel.low.actual", "engine.rpm", "throttle.actual", "lambda.actual", "injector.duty"], message: "Fuel pressure significantly below requested target.", possibleCauses: ["HPFP flow limitation", "Fuel supply limitation", "Pressure control issue"], criticalCondition: { left: "[fuel.high.actual]", operator: "<", right: "[fuel.high.target] * CRITICAL_RATIO" } }),
    rule({ id: "fuel-pressure-sudden-drop", name: "Fuel Pressure Sudden Drop", category: "Fuel", severity: "critical", detector: "rate", conditions: loadConditions, parameters: { DROP_RATE: -500, MIN_THROTTLE: 80, MIN_RPM: 2500 }, durationMs: 30, recommendedChannels: ["fuel.high.actual", "fuel.high.target", "fuel.low.actual", "engine.rpm", "throttle.actual"], message: "Fuel pressure fell at an implausibly high rate under load.", possibleCauses: ["Fuel supply interruption", "Pressure sensor/data anomaly"], detectorOptions: { channel: "fuel.high.actual", operator: "<", thresholdParameter: "DROP_RATE", peakDirection: "min" } }),
    rule({ id: "lambda-lean-vs-target", name: "Lambda Lean vs Target", category: "Fuel", severity: "critical", conditions: [{ left: "[lambda.actual]", operator: ">", right: "[lambda.target] + LEAN_ERROR" }, ...loadConditions], parameters: { LEAN_ERROR: 0.08, CRITICAL_ERROR: 0.15, MIN_THROTTLE: 80, MIN_RPM: 2500 }, durationMs: 120, recommendedChannels: ["lambda.actual", "lambda.target", "engine.rpm", "throttle.actual", "boost.actual", "fuel.high.actual"], message: "Mixture remained leaner than target under load.", possibleCauses: ["Fuel delivery limitation", "Air or lambda measurement deviation"], criticalCondition: { left: "[lambda.actual]", operator: ">", right: "[lambda.target] + CRITICAL_ERROR" } }),
    rule({ id: "injector-duty-saturation", name: "Injector Duty Saturation", category: "Fuel", severity: "warning", conditions: [{ left: "[injector.duty]", operator: ">", right: "WARNING_DUTY" }], parameters: { WARNING_DUTY: 95, CRITICAL_DUTY: 99.5 }, durationMs: 200, recommendedChannels: ["injector.duty", "engine.rpm", "boost.actual", "lambda.actual", "fuel.high.actual"], message: "Injector duty approached the configured capacity limit.", possibleCauses: ["Injector capacity approaching limit"], criticalCondition: { left: "[injector.duty]", operator: ">", right: "CRITICAL_DUTY" } }),
    rule({ id: "excessive-fuel-trims", name: "Excessive Fuel Trims", category: "Fuel", severity: "warning", conditions: [{ left: "abs([fuel.stft])", operator: ">", right: "STFT_LIMIT" }, { left: "abs([fuel.ltft])", operator: ">", right: "LTFT_LIMIT" }], parameters: { STFT_LIMIT: 15, LTFT_LIMIT: 12 }, durationMs: 500, recommendedChannels: ["fuel.stft", "fuel.ltft", "lambda.actual", "engine.rpm"], message: "Persistent fuel correction exceeded the configured range.", possibleCauses: ["Fuel delivery or air measurement deviation"], detectorOptions: { conditionMode: "any" } }),
    rule({ id: "high-intake-air-temperature", name: "High Intake Air Temperature", category: "Temperature", severity: "warning", conditions: [{ left: "[temperature.iat]", operator: ">", right: "WARNING_TEMP" }], parameters: { WARNING_TEMP: 60, CRITICAL_TEMP: 80 }, durationMs: 1000, recommendedChannels: ["temperature.iat", "engine.rpm", "boost.actual", "throttle.actual"], message: "Intake air temperature exceeded the configured threshold.", possibleCauses: ["Heat soak", "High ambient or charge-air temperature"], criticalCondition: { left: "[temperature.iat]", operator: ">", right: "CRITICAL_TEMP" } }),
    rule({ id: "engine-overheating", name: "Engine Overheating", category: "Temperature", severity: "warning", conditions: [{ left: "[temperature.coolant]", operator: ">", right: "WARNING_TEMP" }], parameters: { WARNING_TEMP: 110, CRITICAL_TEMP: 120 }, durationMs: 500, recommendedChannels: ["temperature.coolant", "engine.rpm", "vehicle.speed"], message: "Engine coolant temperature exceeded the configured threshold.", possibleCauses: ["Cooling system load", "Insufficient heat rejection"], criticalCondition: { left: "[temperature.coolant]", operator: ">", right: "CRITICAL_TEMP" } }),
    rule({ id: "cam-target-deviation", name: "Cam Target Deviation", category: "Engine", severity: "warning", conditions: [{ left: "abs([cam.intake.actual] - [cam.intake.target])", operator: ">", right: "MAX_ERROR" }, { left: "abs([cam.exhaust.actual] - [cam.exhaust.target])", operator: ">", right: "MAX_ERROR" }], parameters: { MAX_ERROR: 10, CRITICAL_ERROR: 18 }, durationMs: 200, recommendedChannels: ["engine.rpm", "cam.intake.actual", "cam.intake.target", "cam.exhaust.actual", "cam.exhaust.target"], message: "Cam angle did not track its target within the configured tolerance.", possibleCauses: ["Delayed cam response", "Cam control deviation"], detectorOptions: { conditionMode: "any" } }),
    rule({ id: "transmission-slip", name: "TCC / Transmission Slip", category: "Transmission", severity: "warning", conditions: [{ left: "abs([transmission.tccSlip])", operator: ">", right: "MAX_SLIP" }, { left: "[transmission.gear]", operator: ">=", right: "MIN_GEAR" }, { left: "[throttle.actual]", operator: ">", right: "MIN_THROTTLE" }], parameters: { MAX_SLIP: 250, CRITICAL_SLIP: 500, MIN_GEAR: 3, MIN_THROTTLE: 30 }, durationMs: 300, recommendedChannels: ["transmission.tccSlip", "transmission.gear", "engine.rpm", "throttle.actual"], message: "Transmission or converter slip exceeded the configured threshold.", possibleCauses: ["Converter clutch slip", "Transmission ratio deviation"] }),
    rule({ id: "wheel-speed-mismatch", name: "Wheel Speed Mismatch", category: "Wheel Speed", severity: "warning", detector: "wheel-mismatch", parameters: { MAX_MISMATCH: 8, CRITICAL_MISMATCH: 20, MIN_SPEED: 20 }, durationMs: 100, recommendedChannels: ["wheel.speed.*", "vehicle.speed", "throttle.actual"], message: "Wheel speeds disagreed beyond the configured tolerance.", possibleCauses: ["Wheel slip", "Wheel-speed sensor deviation"], detectorOptions: { group: "wheel.speed", thresholdParameter: "MAX_MISMATCH", minimumSpeedParameter: "MIN_SPEED" } }),
    rule({ id: "wheel-speed-spike", name: "Wheel Speed Spike", category: "Wheel Speed", severity: "warning", detector: "wheel-spike", parameters: { MAX_DEVIATION: 15, CRITICAL_DEVIATION: 30 }, durationMs: 20, recommendedChannels: ["wheel.speed.*", "vehicle.speed"], message: "A wheel-speed channel briefly deviated from the other wheels.", possibleCauses: ["Wheel-speed sensor spike", "Logger data glitch"], detectorOptions: { group: "wheel.speed", thresholdParameter: "MAX_DEVIATION" } }),
    rule({ id: "sensor-dropout", name: "Sensor / Data Dropout", category: "Sensors", severity: "warning", detector: "dropout", parameters: { MIN_SAMPLES: 2 }, recommendedChannels: ["engine.rpm", "boost.actual", "fuel.high.actual", "lambda.actual", "wheel.speed.*"], message: "A signal contained a missing, zero-reset or invalid segment.", possibleCauses: ["Sensor dropout", "Logger data gap"], detectorOptions: { candidates: ["boost.actual", "fuel.high.actual", "lambda.actual", "temperature.iat", "wheel.speed.*"], minimumSamplesParameter: "MIN_SAMPLES" } }),
    rule({ id: "sensor-impossible-rate", name: "Sensor Impossible Rate of Change", category: "Sensors", severity: "warning", detector: "impossible-rate", parameters: { WHEEL_RATE: 1800, BOOST_RATE: 15, TEMPERATURE_RATE: 80 }, durationMs: 10, recommendedChannels: ["wheel.speed.*", "boost.actual", "temperature.iat", "temperature.coolant"], message: "A signal changed faster than the configured plausibility limit.", possibleCauses: ["Sensor spike", "Data conversion or logger issue"], detectorOptions: { candidates: ["wheel.speed.*", "boost.actual", "temperature.iat", "temperature.coolant"], wheelRateParameter: "WHEEL_RATE", boostRateParameter: "BOOST_RATE", temperatureRateParameter: "TEMPERATURE_RATE" } }),
    rule({ id: "stuck-sensor", name: "Stuck Sensor", category: "Sensors", severity: "info", detector: "stuck", parameters: { DURATION_MS: 2000, RPM_CHANGE: 500, EPSILON: 0.000001 }, recommendedChannels: ["throttle.actual", "boost.actual", "fuel.high.actual", "temperature.iat", "engine.rpm"], message: "A signal remained exactly fixed while operating conditions changed.", possibleCauses: ["Stuck sensor value", "Low logger resolution or inactive signal"], detectorOptions: { candidates: ["throttle.actual", "boost.actual", "fuel.high.actual", "temperature.iat"], durationParameter: "DURATION_MS", rpmChangeParameter: "RPM_CHANGE", epsilonParameter: "EPSILON" } }),
    rule({ id: "gear-shift-detection", name: "Gear Shift", category: "Transmission", severity: "info", detector: "gear-shift", parameters: { SETTLE_MS: 300 }, recommendedChannels: ["transmission.gear", "engine.rpm", "throttle.actual", "torque.actual", "ignition.total"], message: "A gear change was detected.", detectorOptions: { channel: "transmission.gear", settleParameter: "SETTLE_MS" } }),
    rule({ id: "rev-limiter-detection", name: "Rev Limiter Intervention", category: "Engine", severity: "info", conditions: [{ left: "[engine.rpm]", operator: ">", right: "LIMITER_RPM" }, { left: "[driver.pedal]", operator: ">", right: "MIN_PEDAL" }], parameters: { LIMITER_RPM: 6800, MIN_PEDAL: 80 }, durationMs: 50, recommendedChannels: ["engine.rpm", "driver.pedal", "throttle.actual", "torque.request", "ignition.total"], message: "Engine speed reached the configured limiter region.", possibleCauses: ["Expected rev limiter intervention"] }),
    rule({ id: "wot-pull-detection", name: "WOT Pull", category: "Engine", severity: "info", detector: "pull", parameters: { MIN_THROTTLE: 90, MIN_DURATION_MS: 1000, MIN_RPM_GAIN: 500 }, recommendedChannels: ["engine.rpm", "driver.pedal", "throttle.actual", "boost.actual", "lambda.actual", "torque.actual", "temperature.iat", "transmission.gear"], message: "Wide-open-throttle acceleration pull detected.", detectorOptions: { throttleParameter: "MIN_THROTTLE", durationParameter: "MIN_DURATION_MS", rpmGainParameter: "MIN_RPM_GAIN" } }),
  ];
}
