"use client";

import { useMemo, useState } from "react";
import { Copy, RotateCcw, Search, Settings2, Trash2, X } from "lucide-react";
import { collectParameters, parseFormula } from "@/domain/formula";
import type { DiagnosticProfile, DiagnosticRuleConfig } from "@/domain/types";
import { createDiagnosticRuleRepository } from "@/diagnostics/persistence/LocalStorageDiagnosticRuleRepository";
import { useWorkspaceStore } from "@/state/workspace-store";
import { AccessibleDialog } from "@/components/AccessibleDialog";

interface Props { open: boolean; onClose: () => void; onRerun: (profile: DiagnosticProfile) => void; }

export function DiagnosticRulesManager({ open, onClose, onRerun }: Props) {
  const { diagnosticProfiles, activeDiagnosticProfileId, setDiagnosticProfiles, setActiveDiagnosticProfileId, diagnosticsRunning } = useWorkspaceStore();
  const [query, setQuery] = useState(""); const [modifiedOnly, setModifiedOnly] = useState(false); const [editing, setEditing] = useState<DiagnosticRuleConfig | null>(null); const [error, setError] = useState("");
  const active = diagnosticProfiles.find((profile) => profile.id === activeDiagnosticProfileId) ?? diagnosticProfiles[0];
  const rules = useMemo(() => (active?.rules ?? []).filter((rule) => rule.name.toLowerCase().includes(query.toLowerCase()) && (!modifiedOnly || rule.modified)), [active, query, modifiedOnly]);
  if (!open || !active) return null;
  const repository = createDiagnosticRuleRepository();
  const refresh = () => setDiagnosticProfiles(repository.loadProfiles(), repository.getActiveProfileId());
  const saveRule = (rule: DiagnosticRuleConfig) => { const profile = { ...active, rules: active.rules.map((item) => item.id === rule.id ? rule : item) }; repository.saveProfile(profile); refresh(); setEditing(null); };
  const toggle = (rule: DiagnosticRuleConfig) => saveRule({ ...rule, enabled: !rule.enabled, modified: true });
  const duplicateProfile = () => { const name = window.prompt("New diagnostic profile name", `${active.name} copy`); if (!name) return; const profile: DiagnosticProfile = { ...structuredClone(active), id: `profile-${crypto.randomUUID()}`, name, origin: "user", vehicleSpecific: true, rules: active.rules.map((rule) => ({ ...rule, modified: false })) }; repository.saveProfile(profile); repository.setActiveProfileId(profile.id); refresh(); };
  const duplicateRule = (rule: DiagnosticRuleConfig) => { const copy: DiagnosticRuleConfig = { ...structuredClone(rule), id: `custom-${crypto.randomUUID()}`, name: `${rule.name} copy`, origin: "user", modified: true }; const profile = { ...active, rules: [...active.rules, copy] }; repository.saveProfile(profile); refresh(); };
  const deleteRule = (rule: DiagnosticRuleConfig) => { if (rule.origin !== "user" || !window.confirm(`Delete custom rule “${rule.name}”?`)) return; repository.saveProfile({ ...active, rules: active.rules.filter((item) => item.id !== rule.id) }); refresh(); };
  const resetRule = (rule: DiagnosticRuleConfig) => { repository.resetRule(active.id, rule.id); refresh(); };
  const resetAll = () => { if (!window.confirm("Reset every built-in rule to its current default? Custom rules will be kept.")) return; repository.resetAllBuiltInRules(active.id); refresh(); };
  const selectProfile = (id: string) => { repository.setActiveProfileId(id); setActiveDiagnosticProfileId(id); };
  return <AccessibleDialog className="rules-modal" ariaLabelledBy="diagnostic-rules-title" onClose={onClose}><header><div><span className="eyebrow">DIAGNOSTICS CONFIGURATION</span><h2 id="diagnostic-rules-title">Diagnostic Rules</h2><p>Thresholds are generic defaults. Tune them for the vehicle and use case.</p></div><button aria-label="Close diagnostic rules" onClick={onClose}><X size={18} /></button></header>
    <div className="rules-toolbar"><label><span>ACTIVE PROFILE</span><select value={active.id} onChange={(event) => selectProfile(event.target.value)}>{diagnosticProfiles.map((profile) => <option key={profile.id} value={profile.id}>{profile.name}</option>)}</select></label><button className="button secondary" onClick={duplicateProfile}><Copy size={13} /> Duplicate profile</button><button className="button secondary" onClick={resetAll}><RotateCcw size={13} /> Reset built-ins</button><button className="button primary" disabled={diagnosticsRunning} onClick={() => onRerun(active)}>{diagnosticsRunning ? "Analyzing…" : "Re-run diagnostics"}</button></div>
    <div className="rules-layout"><section className="rules-list"><div className="rules-search"><Search size={14} /><input aria-label="Search diagnostic rules" placeholder="Search rules" value={query} onChange={(event) => setQuery(event.target.value)} /><label><input type="checkbox" checked={modifiedOnly} onChange={(event) => setModifiedOnly(event.target.checked)} /> Modified only</label></div>{rules.map((rule) => <article key={rule.id} className={!rule.enabled ? "disabled" : ""}><button aria-label={`${rule.enabled ? "Disable" : "Enable"} ${rule.name}`} aria-pressed={rule.enabled} className={`rule-check ${rule.enabled ? "on" : ""}`} onClick={() => toggle(rule)}>{rule.enabled ? "✓" : ""}</button><div><b>{rule.name}</b><span>{rule.category} · {rule.severity} · {rule.origin === "default" ? `Built-in${rule.modified ? " · Modified" : ""}` : "Custom"}</span></div><button onClick={() => { setEditing(structuredClone(rule)); setError(""); }}><Settings2 size={13} /> Edit</button><button aria-label={`Duplicate ${rule.name}`} onClick={() => duplicateRule(rule)}><Copy size={13} /></button>{rule.origin === "default" ? <button aria-label={`Reset ${rule.name} to default`} disabled={!rule.modified} onClick={() => resetRule(rule)}><RotateCcw size={13} /></button> : <button aria-label={`Delete ${rule.name}`} onClick={() => deleteRule(rule)}><Trash2 size={13} /></button>}</article>)}</section>
      <section className="rule-editor">{editing ? <RuleEditor rule={editing} error={error} onCancel={() => setEditing(null)} onChange={setEditing} onSave={() => { try { const expressions = [...editing.conditions.flatMap((condition) => [condition.left, condition.right]), ...(editing.criticalCondition ? [editing.criticalCondition.left, editing.criticalCondition.right] : [])]; const parameters = new Set(expressions.flatMap((expression) => Array.from(collectParameters(parseFormula(expression))))); const missing = Array.from(parameters).filter((name) => editing.parameters[name] === undefined); if (missing.length) throw new Error(`Unknown rule parameter${missing.length > 1 ? "s" : ""}: ${missing.join(", ")}`); saveRule({ ...editing, modified: true }); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Invalid rule expression"); } }} /> : <div className="rule-editor-empty"><Settings2 size={25} /><b>Select a rule to edit</b><span>Conditions use the same safe expression parser as calculated channels.</span></div>}</section></div>
  </AccessibleDialog>;
}

function RuleEditor({ rule, error, onChange, onSave, onCancel }: { rule: DiagnosticRuleConfig; error: string; onChange: (rule: DiagnosticRuleConfig) => void; onSave: () => void; onCancel: () => void }) {
  const patch = (value: Partial<DiagnosticRuleConfig>) => onChange({ ...rule, ...value });
  return <><div className="rule-editor-title"><div><span>EDIT RULE</span><h3>{rule.name}</h3></div><span className={`severity-badge ${rule.severity}`}>{rule.severity}</span></div><div className="control-grid"><label className="field"><span>Name</span><input value={rule.name} onChange={(event) => patch({ name: event.target.value })} /></label><label className="field"><span>Severity</span><select value={rule.severity} onChange={(event) => patch({ severity: event.target.value as DiagnosticRuleConfig["severity"] })}><option value="critical">Critical</option><option value="warning">Warning</option><option value="info">Info</option></select></label></div><div className="rule-flags"><label className="rule-enabled"><input type="checkbox" checked={rule.enabled} onChange={(event) => patch({ enabled: event.target.checked })} /> Rule enabled</label><label className="rule-enabled"><input type="checkbox" checked={rule.wotOnly} disabled={rule.detector === "pull"} onChange={(event) => patch({ wotOnly: event.target.checked })} /> WOT area only</label></div>
    <h4>WHEN</h4>{rule.conditions.map((condition, index) => <div className="condition-edit" key={index}><input value={condition.left} onChange={(event) => patch({ conditions: rule.conditions.map((item, itemIndex) => itemIndex === index ? { ...item, left: event.target.value } : item) })} /><select value={condition.operator} onChange={(event) => patch({ conditions: rule.conditions.map((item, itemIndex) => itemIndex === index ? { ...item, operator: event.target.value as typeof item.operator } : item) })}>{["<", "<=", ">", ">=", "==", "!="].map((operator) => <option key={operator}>{operator}</option>)}</select><input value={condition.right} onChange={(event) => patch({ conditions: rule.conditions.map((item, itemIndex) => itemIndex === index ? { ...item, right: event.target.value } : item) })} /><button aria-label="Remove condition" onClick={() => patch({ conditions: rule.conditions.filter((_, itemIndex) => itemIndex !== index) })}><X size={12} /></button></div>)}<button className="add-condition" onClick={() => patch({ conditions: [...rule.conditions, { left: "[engine.rpm]", operator: ">", right: "MIN_RPM" }] })}>+ Add condition</button>
    <div className="control-grid"><label className="field"><span>Duration, ms</span><input type="number" value={rule.durationMs} onChange={(event) => patch({ durationMs: Number(event.target.value) })} /></label><label className="field"><span>Cooldown, ms</span><input type="number" value={rule.cooldownMs} onChange={(event) => patch({ cooldownMs: Number(event.target.value) })} /></label></div><label className="field"><span>Correlation window, ms</span><input type="number" value={rule.correlationWindowMs} onChange={(event) => patch({ correlationWindowMs: Number(event.target.value) })} /></label><h4>PARAMETERS</h4><div className="rule-parameters">{Object.entries(rule.parameters).map(([name, value]) => <label key={name}><span>{name}</span><input type="number" value={value} onChange={(event) => patch({ parameters: { ...rule.parameters, [name]: Number(event.target.value) } })} /></label>)}</div><label className="field"><span>Recommended channels · comma separated canonical names</span><input value={rule.recommendedChannels.join(", ")} onChange={(event) => patch({ recommendedChannels: event.target.value.split(",").map((value) => value.trim()).filter(Boolean) })} /></label><label className="field"><span>Message</span><textarea value={rule.message} onChange={(event) => patch({ message: event.target.value })} /></label>{error && <div className="rule-error" role="alert">{error}</div>}<footer><button className="button secondary" onClick={onCancel}>Cancel</button><button className="button primary" onClick={onSave}>Save rule</button></footer></>;
}
