"use client";

import { useMemo, useState } from "react";
import { Copy, Plus, RotateCcw, Search, Settings2, Trash2, X } from "lucide-react";
import { FORMULA_WINDOW_FUNCTIONS } from "@/domain/formula";
import type { DiagnosticProfile, DiagnosticRuleConfig, SemanticChannelMatch } from "@/domain/types";
import { createCustomDiagnosticRule, DIAGNOSTIC_CATEGORIES, validateDiagnosticRule } from "@/diagnostics/diagnostic-rule-editor";
import { createDiagnosticRuleRepository } from "@/diagnostics/persistence/LocalStorageDiagnosticRuleRepository";
import { useWorkspaceStore } from "@/state/workspace-store";
import { AccessibleDialog } from "@/components/AccessibleDialog";

interface Props { open: boolean; onClose: () => void; onRerun: (profile: DiagnosticProfile) => void; }

export function DiagnosticRulesManager({ open, onClose, onRerun }: Props) {
  const { diagnosticProfiles, activeDiagnosticProfileId, setDiagnosticProfiles, setActiveDiagnosticProfileId, diagnosticsRunning, diagnostics } = useWorkspaceStore();
  const [query, setQuery] = useState(""); const [modifiedOnly, setModifiedOnly] = useState(false); const [editing, setEditing] = useState<DiagnosticRuleConfig | null>(null); const [error, setError] = useState("");
  const active = diagnosticProfiles.find((profile) => profile.id === activeDiagnosticProfileId) ?? diagnosticProfiles[0];
  const rules = useMemo(() => (active?.rules ?? []).filter((rule) => rule.name.toLowerCase().includes(query.toLowerCase()) && (!modifiedOnly || rule.modified)), [active, query, modifiedOnly]);
  if (!open || !active) return null;
  const repository = createDiagnosticRuleRepository();
  const refresh = () => setDiagnosticProfiles(repository.loadProfiles(), repository.getActiveProfileId());
  const saveRule = (rule: DiagnosticRuleConfig) => { const exists = active.rules.some((item) => item.id === rule.id); const profile = { ...active, rules: exists ? active.rules.map((item) => item.id === rule.id ? rule : item) : [...active.rules, rule] }; repository.saveProfile(profile); refresh(); setEditing(null); };
  const toggle = (rule: DiagnosticRuleConfig) => saveRule({ ...rule, enabled: !rule.enabled, modified: true });
  const duplicateProfile = () => { const name = window.prompt("New diagnostic profile name", `${active.name} copy`); if (!name) return; const profile: DiagnosticProfile = { ...structuredClone(active), id: `profile-${crypto.randomUUID()}`, name, origin: "user", vehicleSpecific: true, rules: active.rules.map((rule) => ({ ...rule, modified: false })) }; repository.saveProfile(profile); repository.setActiveProfileId(profile.id); refresh(); };
  const duplicateRule = (rule: DiagnosticRuleConfig) => { const copy: DiagnosticRuleConfig = { ...structuredClone(rule), id: `custom-${crypto.randomUUID()}`, name: `${rule.name} copy`, origin: "user", modified: true }; const profile = { ...active, rules: [...active.rules, copy] }; repository.saveProfile(profile); refresh(); };
  const createRule = () => { setEditing(createCustomDiagnosticRule(`custom-${crypto.randomUUID()}`)); setError(""); };
  const deleteRule = (rule: DiagnosticRuleConfig) => { if (rule.origin !== "user" || !window.confirm(`Delete custom rule “${rule.name}”?`)) return; repository.saveProfile({ ...active, rules: active.rules.filter((item) => item.id !== rule.id) }); refresh(); };
  const resetRule = (rule: DiagnosticRuleConfig) => { repository.resetRule(active.id, rule.id); refresh(); };
  const resetAll = () => { if (!window.confirm("Reset every built-in rule to its current default? Custom rules will be kept.")) return; repository.resetAllBuiltInRules(active.id); refresh(); };
  const selectProfile = (id: string) => { repository.setActiveProfileId(id); setActiveDiagnosticProfileId(id); };
  return <AccessibleDialog className="rules-modal" ariaLabelledBy="diagnostic-rules-title" onClose={onClose}><header><div><span className="eyebrow">DIAGNOSTICS CONFIGURATION</span><h2 id="diagnostic-rules-title">Diagnostic Rules</h2><p>Thresholds are generic defaults. Tune them for the vehicle and use case.</p></div><button aria-label="Close diagnostic rules" onClick={onClose}><X size={18} /></button></header>
    <div className="rules-toolbar"><label><span>ACTIVE PROFILE</span><select value={active.id} onChange={(event) => selectProfile(event.target.value)}>{diagnosticProfiles.map((profile) => <option key={profile.id} value={profile.id}>{profile.name}</option>)}</select></label><button className="button primary" onClick={createRule}><Plus size={13} /> New rule</button><button className="button secondary" onClick={duplicateProfile}><Copy size={13} /> Duplicate profile</button><button className="button secondary" onClick={resetAll}><RotateCcw size={13} /> Reset built-ins</button><button className="button primary" disabled={diagnosticsRunning} onClick={() => onRerun(active)}>{diagnosticsRunning ? "Analyzing…" : "Re-run diagnostics"}</button></div>
    <div className="rules-layout"><section className="rules-list"><div className="rules-search"><Search size={14} /><input aria-label="Search diagnostic rules" placeholder="Search rules" value={query} onChange={(event) => setQuery(event.target.value)} /><label><input type="checkbox" checked={modifiedOnly} onChange={(event) => setModifiedOnly(event.target.checked)} /> Modified only</label></div>{rules.map((rule) => <article key={rule.id} className={!rule.enabled ? "disabled" : ""}><button aria-label={`${rule.enabled ? "Disable" : "Enable"} ${rule.name}`} aria-pressed={rule.enabled} className={`rule-check ${rule.enabled ? "on" : ""}`} onClick={() => toggle(rule)}>{rule.enabled ? "✓" : ""}</button><div><b>{rule.name}</b><span>{rule.category} · {rule.severity} · {rule.origin === "default" ? `Built-in${rule.modified ? " · Modified" : ""}` : "Custom"}</span></div><button onClick={() => { setEditing(structuredClone(rule)); setError(""); }}><Settings2 size={13} /> Edit</button><button aria-label={`Duplicate ${rule.name}`} onClick={() => duplicateRule(rule)}><Copy size={13} /></button>{rule.origin === "default" ? <button aria-label={`Reset ${rule.name} to default`} disabled={!rule.modified} onClick={() => resetRule(rule)}><RotateCcw size={13} /></button> : <button aria-label={`Delete ${rule.name}`} onClick={() => deleteRule(rule)}><Trash2 size={13} /></button>}</article>)}</section>
      <section className="rule-editor">{editing ? <RuleEditor rule={editing} mappings={diagnostics?.semanticMapping ?? []} error={error} onCancel={() => setEditing(null)} onChange={setEditing} onSave={() => { const validationError = validateDiagnosticRule(editing); if (validationError) { setError(validationError); return; } saveRule({ ...editing, modified: true }); setError(""); }} /> : <div className="rule-editor-empty"><Settings2 size={25} /><b>Select a rule to edit</b><span>Conditions use the same safe expression parser as calculated channels.</span></div>}</section></div>
  </AccessibleDialog>;
}

function RuleEditor({ rule, mappings, error, onChange, onSave, onCancel }: { rule: DiagnosticRuleConfig; mappings: SemanticChannelMatch[]; error: string; onChange: (rule: DiagnosticRuleConfig) => void; onSave: () => void; onCancel: () => void }) {
  const patch = (value: Partial<DiagnosticRuleConfig>) => onChange({ ...rule, ...value });
  const addParameter = () => { const requested = window.prompt("Parameter name", "THRESHOLD"); if (!requested) return; const name = requested.trim(); if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(name)) { window.alert("Use letters, numbers, and underscores; the first character cannot be a number."); return; } if (rule.parameters[name] !== undefined) { window.alert(`Parameter ${name} already exists.`); return; } patch({ parameters: { ...rule.parameters, [name]: 0 } }); };
  const removeParameter = (name: string) => { const parameters = { ...rule.parameters }; delete parameters[name]; patch({ parameters }); };
  const wrapWithWindowFunction = (conditionIndex: number, functionName: string) => patch({ conditions: rule.conditions.map((condition, index) => index === conditionIndex ? { ...condition, left: `${functionName}(${condition.left || "[engine.rpm]"}, 10)` } : condition) });
  return <><div className="rule-editor-title"><div><span>{rule.origin === "user" ? "CUSTOM RULE" : "EDIT RULE"}</span><h3>{rule.name}</h3></div><span className={`severity-badge ${rule.severity}`}>{rule.severity}</span></div><div className="control-grid"><label className="field"><span>Name</span><input value={rule.name} onChange={(event) => patch({ name: event.target.value })} /></label><label className="field"><span>Category</span><select value={rule.category} onChange={(event) => patch({ category: event.target.value as DiagnosticRuleConfig["category"] })}>{DIAGNOSTIC_CATEGORIES.map((category) => <option key={category}>{category}</option>)}</select></label><label className="field"><span>Severity</span><select value={rule.severity} onChange={(event) => patch({ severity: event.target.value as DiagnosticRuleConfig["severity"] })}><option value="critical">Critical</option><option value="warning">Warning</option><option value="info">Info</option></select></label>{rule.detector === "temporal" && <label className="field"><span>Condition matching</span><select value={rule.detectorOptions.conditionMode === "any" ? "any" : "all"} onChange={(event) => patch({ detectorOptions: { ...rule.detectorOptions, conditionMode: event.target.value } })}><option value="all">All conditions</option><option value="any">Any condition</option></select></label>}</div><div className="rule-flags"><label className="rule-enabled"><input type="checkbox" checked={rule.enabled} onChange={(event) => patch({ enabled: event.target.checked })} /> Rule enabled</label><label className="rule-enabled"><input type="checkbox" checked={rule.wotOnly} disabled={rule.detector === "pull"} onChange={(event) => patch({ wotOnly: event.target.checked })} /> WOT area only</label></div>{mappings.length > 0 && <details className="rule-channel-mapping"><summary>Mapped channels in this log <b>{mappings.length}</b></summary><div>{mappings.map((mapping) => <span key={`${mapping.canonical}-${mapping.channelId}`}><code>[{mapping.canonical}]</code><i>→</i>{mapping.channelName}</span>)}</div></details>}
    <h4>WHEN</h4>{rule.conditions.map((condition, index) => <div className="condition-edit" key={index}><input aria-label={`Left expression ${index + 1}`} value={condition.left} onChange={(event) => patch({ conditions: rule.conditions.map((item, itemIndex) => itemIndex === index ? { ...item, left: event.target.value } : item) })} /><select aria-label={`Window function ${index + 1}`} value="" onChange={(event) => { if (event.target.value) wrapWithWindowFunction(index, event.target.value); }}><option value="">ƒ window</option>{FORMULA_WINDOW_FUNCTIONS.map((name) => <option key={name} value={name}>{name}</option>)}</select><select aria-label={`Operator ${index + 1}`} value={condition.operator} onChange={(event) => patch({ conditions: rule.conditions.map((item, itemIndex) => itemIndex === index ? { ...item, operator: event.target.value as typeof item.operator } : item) })}>{["<", "<=", ">", ">=", "==", "!="].map((operator) => <option key={operator}>{operator}</option>)}</select><input aria-label={`Right expression ${index + 1}`} value={condition.right} onChange={(event) => patch({ conditions: rule.conditions.map((item, itemIndex) => itemIndex === index ? { ...item, right: event.target.value } : item) })} /><button aria-label="Remove condition" onClick={() => patch({ conditions: rule.conditions.filter((_, itemIndex) => itemIndex !== index) })}><X size={12} /></button></div>)}<button className="add-condition" onClick={() => patch({ conditions: [...rule.conditions, { left: "[engine.rpm]", operator: ">", right: "MIN_RPM" }] })}>+ Add condition</button><p className="window-function-help"><b>Window size is a sample count.</b> `lag` returns an older value; `delta` returns its change; `moving_avg`, `moving_min`, `moving_max`, and `moving_sum` aggregate a complete trailing window.</p>
    <div className="control-grid"><label className="field"><span>Duration, ms</span><input type="number" min="0" value={rule.durationMs} onChange={(event) => patch({ durationMs: Number(event.target.value) })} /></label><label className="field"><span>Cooldown, ms</span><input type="number" min="0" value={rule.cooldownMs} onChange={(event) => patch({ cooldownMs: Number(event.target.value) })} /></label></div><label className="field"><span>Correlation window, ms</span><input type="number" min="0" value={rule.correlationWindowMs} onChange={(event) => patch({ correlationWindowMs: Number(event.target.value) })} /></label><div className="rule-section-heading"><h4>PARAMETERS</h4><button type="button" onClick={addParameter}><Plus size={12} /> Add parameter</button></div><div className="rule-parameters">{Object.entries(rule.parameters).map(([name, value]) => <label key={name}><span>{name}</span><input type="number" value={value} onChange={(event) => patch({ parameters: { ...rule.parameters, [name]: Number(event.target.value) } })} /><button type="button" aria-label={`Remove parameter ${name}`} onClick={() => removeParameter(name)}><X size={12} /></button></label>)}</div><label className="field"><span>Recommended channels · comma separated canonical names</span><input value={rule.recommendedChannels.join(", ")} onChange={(event) => patch({ recommendedChannels: event.target.value.split(",").map((value) => value.trim()).filter(Boolean) })} /></label><label className="field"><span>Message</span><textarea value={rule.message} onChange={(event) => patch({ message: event.target.value })} /></label><label className="field"><span>Possible causes · one per line</span><textarea value={rule.possibleCauses.join("\n")} onChange={(event) => patch({ possibleCauses: event.target.value.split("\n").map((value) => value.trim()).filter(Boolean) })} /></label>{error && <div className="rule-error" role="alert">{error}</div>}<footer><button className="button secondary" onClick={onCancel}>Cancel</button><button className="button primary" onClick={onSave}>Save rule</button></footer></>;
}
